/** Zona waktu Indonesia. */
export type Zona = 'WIB' | 'WITA' | 'WIT';

/** Peta zona → identifier IANA untuk Intl.DateTimeFormat. */
export const ZONA_TZ: Record<Zona, string> = {
  WIB: 'Asia/Jakarta',
  WITA: 'Asia/Makassar',
  WIT: 'Asia/Jayapura',
};

/** Daftar kota kurasi (69) — JANGAN tambah/kurang tanpa keputusan pemilik. */
export const KOTA: { nama: string; zona: Zona }[] = [
  // WIB (34)
  { nama: 'Jakarta', zona: 'WIB' },
  { nama: 'Bandung', zona: 'WIB' },
  { nama: 'Bekasi', zona: 'WIB' },
  { nama: 'Depok', zona: 'WIB' },
  { nama: 'Tangerang', zona: 'WIB' },
  { nama: 'Bogor', zona: 'WIB' },
  { nama: 'Serang', zona: 'WIB' },
  { nama: 'Cirebon', zona: 'WIB' },
  { nama: 'Semarang', zona: 'WIB' },
  { nama: 'Yogyakarta', zona: 'WIB' },
  { nama: 'Surakarta', zona: 'WIB' },
  { nama: 'Purwokerto', zona: 'WIB' },
  { nama: 'Tegal', zona: 'WIB' },
  { nama: 'Surabaya', zona: 'WIB' },
  { nama: 'Malang', zona: 'WIB' },
  { nama: 'Kediri', zona: 'WIB' },
  { nama: 'Jember', zona: 'WIB' },
  { nama: 'Banyuwangi', zona: 'WIB' },
  { nama: 'Madiun', zona: 'WIB' },
  { nama: 'Banda Aceh', zona: 'WIB' },
  { nama: 'Medan', zona: 'WIB' },
  { nama: 'Padang', zona: 'WIB' },
  { nama: 'Bukittinggi', zona: 'WIB' },
  { nama: 'Pekanbaru', zona: 'WIB' },
  { nama: 'Batam', zona: 'WIB' },
  { nama: 'Tanjungpinang', zona: 'WIB' },
  { nama: 'Jambi', zona: 'WIB' },
  { nama: 'Palembang', zona: 'WIB' },
  { nama: 'Bengkulu', zona: 'WIB' },
  { nama: 'Bandar Lampung', zona: 'WIB' },
  { nama: 'Pangkalpinang', zona: 'WIB' },
  { nama: 'Pontianak', zona: 'WIB' },
  { nama: 'Singkawang', zona: 'WIB' },
  { nama: 'Palangka Raya', zona: 'WIB' },
  // WITA (22)
  { nama: 'Denpasar', zona: 'WITA' },
  { nama: 'Mataram', zona: 'WITA' },
  { nama: 'Bima', zona: 'WITA' },
  { nama: 'Kupang', zona: 'WITA' },
  { nama: 'Labuan Bajo', zona: 'WITA' },
  { nama: 'Banjarmasin', zona: 'WITA' },
  { nama: 'Banjarbaru', zona: 'WITA' },
  { nama: 'Balikpapan', zona: 'WITA' },
  { nama: 'Samarinda', zona: 'WITA' },
  { nama: 'Bontang', zona: 'WITA' },
  { nama: 'Nusantara (IKN)', zona: 'WITA' },
  { nama: 'Tarakan', zona: 'WITA' },
  { nama: 'Tanjung Selor', zona: 'WITA' },
  { nama: 'Makassar', zona: 'WITA' },
  { nama: 'Parepare', zona: 'WITA' },
  { nama: 'Baubau', zona: 'WITA' },
  { nama: 'Palu', zona: 'WITA' },
  { nama: 'Kendari', zona: 'WITA' },
  { nama: 'Gorontalo', zona: 'WITA' },
  { nama: 'Manado', zona: 'WITA' },
  { nama: 'Bitung', zona: 'WITA' },
  { nama: 'Mamuju', zona: 'WITA' },
  // WIT (13)
  { nama: 'Ambon', zona: 'WIT' },
  { nama: 'Ternate', zona: 'WIT' },
  { nama: 'Tidore', zona: 'WIT' },
  { nama: 'Sofifi', zona: 'WIT' },
  { nama: 'Jayapura', zona: 'WIT' },
  { nama: 'Merauke', zona: 'WIT' },
  { nama: 'Sorong', zona: 'WIT' },
  { nama: 'Manokwari', zona: 'WIT' },
  { nama: 'Timika', zona: 'WIT' },
  { nama: 'Biak', zona: 'WIT' },
  { nama: 'Nabire', zona: 'WIT' },
  { nama: 'Fakfak', zona: 'WIT' },
  { nama: 'Wamena', zona: 'WIT' },
];
