import {
  BookOpen,
  ClipboardList,
  FileText,
  CheckSquare,
  Lightbulb,
  MessageSquare,
  Zap,
  Mail,
} from 'lucide-react'
import type { ToolDefinition } from './types'

export const TOOLS: ToolDefinition[] = [
  {
    id: 'modul-ajar',
    title: 'Modul Ajar',
    description: 'Buat modul ajar Kurikulum Merdeka lengkap dengan kegiatan dan asesmen.',
    Icon: BookOpen,
    fields: [
      { id: 'mapel', label: 'Mata Pelajaran', type: 'text', placeholder: 'contoh: Matematika', required: true },
      {
        id: 'kelas',
        label: 'Kelas / Fase',
        type: 'select',
        required: true,
        options: [
          { value: 'Fase A (Kelas 1-2 SD)', label: 'Fase A – Kelas 1–2 SD' },
          { value: 'Fase B (Kelas 3-4 SD)', label: 'Fase B – Kelas 3–4 SD' },
          { value: 'Fase C (Kelas 5-6 SD)', label: 'Fase C – Kelas 5–6 SD' },
          { value: 'Fase D (Kelas 7-9 SMP)', label: 'Fase D – Kelas 7–9 SMP' },
          { value: 'Fase E (Kelas 10 SMA)', label: 'Fase E – Kelas 10 SMA' },
          { value: 'Fase F (Kelas 11-12 SMA)', label: 'Fase F – Kelas 11–12 SMA' },
        ],
      },
      { id: 'topik', label: 'Topik / Materi', type: 'text', placeholder: 'contoh: Pecahan Senilai', required: true },
      {
        id: 'waktu',
        label: 'Alokasi Waktu',
        type: 'select',
        required: true,
        options: [
          { value: '2 JP (2 x 35 menit)', label: '2 JP (2 × 35 menit)' },
          { value: '2 JP (2 x 40 menit)', label: '2 JP (2 × 40 menit)' },
          { value: '2 JP (2 x 45 menit)', label: '2 JP (2 × 45 menit)' },
          { value: '3 JP (3 x 35 menit)', label: '3 JP (3 × 35 menit)' },
          { value: '3 JP (3 x 40 menit)', label: '3 JP (3 × 40 menit)' },
          { value: '3 JP (3 x 45 menit)', label: '3 JP (3 × 45 menit)' },
          { value: '4 JP (4 x 45 menit)', label: '4 JP (4 × 45 menit)' },
        ],
      },
      { id: 'catatan', label: 'Catatan Tambahan (opsional)', type: 'textarea', placeholder: 'Konteks khusus, kondisi kelas, dll.', rows: 3 },
      { id: 'islami', label: 'Integrasikan nilai Islami', type: 'toggle', description: 'Sisipkan nilai-nilai Islami yang relevan secara alami dalam kegiatan.' },
    ],
  },
  {
    id: 'bank-soal',
    title: 'Bank Soal',
    description: 'Buat soal pilihan ganda, esai, isian, atau campuran dengan kunci jawaban.',
    Icon: ClipboardList,
    fields: [
      { id: 'mapel', label: 'Mata Pelajaran', type: 'text', placeholder: 'contoh: IPA', required: true },
      {
        id: 'kelas',
        label: 'Kelas',
        type: 'select',
        required: true,
        options: [
          { value: 'Kelas 1 SD', label: 'Kelas 1 SD' },
          { value: 'Kelas 2 SD', label: 'Kelas 2 SD' },
          { value: 'Kelas 3 SD', label: 'Kelas 3 SD' },
          { value: 'Kelas 4 SD', label: 'Kelas 4 SD' },
          { value: 'Kelas 5 SD', label: 'Kelas 5 SD' },
          { value: 'Kelas 6 SD', label: 'Kelas 6 SD' },
          { value: 'Kelas 7 SMP', label: 'Kelas 7 SMP' },
          { value: 'Kelas 8 SMP', label: 'Kelas 8 SMP' },
          { value: 'Kelas 9 SMP', label: 'Kelas 9 SMP' },
          { value: 'Kelas 10 SMA', label: 'Kelas 10 SMA' },
          { value: 'Kelas 11 SMA', label: 'Kelas 11 SMA' },
          { value: 'Kelas 12 SMA', label: 'Kelas 12 SMA' },
        ],
      },
      { id: 'topik', label: 'Topik', type: 'text', placeholder: 'contoh: Sistem Peredaran Darah', required: true },
      {
        id: 'jenisSoal',
        label: 'Jenis Soal',
        type: 'select',
        required: true,
        options: [
          { value: 'Pilihan Ganda', label: 'Pilihan Ganda (PG)' },
          { value: 'Esai', label: 'Esai' },
          { value: 'Isian Singkat', label: 'Isian Singkat' },
          { value: 'Campuran (PG + Esai)', label: 'Campuran (PG + Esai)' },
        ],
      },
      {
        id: 'jumlah',
        label: 'Jumlah Soal',
        type: 'select',
        required: true,
        options: [
          { value: '5', label: '5 soal' },
          { value: '10', label: '10 soal' },
          { value: '15', label: '15 soal' },
        ],
      },
      {
        id: 'tingkat',
        label: 'Tingkat Kesulitan',
        type: 'select',
        required: true,
        options: [
          { value: 'Mudah', label: 'Mudah (C1–C2)' },
          { value: 'Sedang', label: 'Sedang (C2–C3)' },
          { value: 'Sulit', label: 'Sulit (C3–C4)' },
          { value: 'HOTS', label: 'HOTS (C4–C6)' },
        ],
      },
    ],
  },
  {
    id: 'lkpd',
    title: 'LKPD',
    description: 'Buat Lembar Kerja Peserta Didik siap cetak lengkap dengan panduan dan kolom jawaban.',
    Icon: FileText,
    fields: [
      { id: 'mapel', label: 'Mata Pelajaran', type: 'text', placeholder: 'contoh: IPS', required: true },
      {
        id: 'kelas',
        label: 'Kelas',
        type: 'select',
        required: true,
        options: [
          { value: 'Kelas 1–2 SD', label: 'Kelas 1–2 SD' },
          { value: 'Kelas 3–4 SD', label: 'Kelas 3–4 SD' },
          { value: 'Kelas 5–6 SD', label: 'Kelas 5–6 SD' },
          { value: 'Kelas 7–9 SMP', label: 'Kelas 7–9 SMP' },
          { value: 'Kelas 10–12 SMA', label: 'Kelas 10–12 SMA' },
        ],
      },
      { id: 'topik', label: 'Topik', type: 'text', placeholder: 'contoh: Keragaman Budaya Indonesia', required: true },
      { id: 'tujuan', label: 'Tujuan Pembelajaran', type: 'textarea', placeholder: 'Siswa mampu...', required: true, rows: 3 },
      {
        id: 'jenisAktivitas',
        label: 'Jenis Aktivitas',
        type: 'select',
        required: true,
        options: [
          { value: 'Individu', label: 'Individu' },
          { value: 'Kelompok', label: 'Kelompok' },
          { value: 'Eksperimen / Praktik', label: 'Eksperimen / Praktik' },
        ],
      },
    ],
  },
  {
    id: 'rubrik-penilaian',
    title: 'Rubrik Penilaian',
    description: 'Buat tabel rubrik dengan deskriptor jelas untuk menilai kinerja siswa secara objektif.',
    Icon: CheckSquare,
    fields: [
      { id: 'tugas', label: 'Tugas / Kegiatan yang Dinilai', type: 'text', placeholder: 'contoh: Presentasi hasil proyek', required: true },
      {
        id: 'kelas',
        label: 'Kelas',
        type: 'select',
        required: true,
        options: [
          { value: 'SD (Kelas 1–6)', label: 'SD (Kelas 1–6)' },
          { value: 'SMP (Kelas 7–9)', label: 'SMP (Kelas 7–9)' },
          { value: 'SMA (Kelas 10–12)', label: 'SMA (Kelas 10–12)' },
        ],
      },
      { id: 'aspek', label: 'Aspek yang Dinilai', type: 'textarea', placeholder: 'contoh: Isi, Bahasa, Penampilan, Kerja Sama', required: true, rows: 3 },
      {
        id: 'skala',
        label: 'Skala Penilaian',
        type: 'select',
        required: true,
        options: [
          { value: '1–4', label: '1–4' },
          { value: '1–5', label: '1–5' },
          { value: '1–100', label: '1–100' },
          { value: 'A/B/C/D', label: 'A / B / C / D' },
        ],
      },
    ],
  },
  {
    id: 'penyederhana-materi',
    title: 'Penyederhana Materi',
    description: 'Ubah materi pelajaran yang rumit menjadi penjelasan yang mudah dipahami siswa.',
    Icon: Lightbulb,
    fields: [
      { id: 'materi', label: 'Materi yang Ingin Disederhanakan', type: 'textarea', placeholder: 'Tempel atau ketik materi di sini...', required: true, rows: 8 },
      {
        id: 'kelas',
        label: 'Untuk Kelas',
        type: 'select',
        required: true,
        options: [
          { value: 'Kelas 1–2 SD', label: 'Kelas 1–2 SD' },
          { value: 'Kelas 3–4 SD', label: 'Kelas 3–4 SD' },
          { value: 'Kelas 5–6 SD', label: 'Kelas 5–6 SD' },
          { value: 'Kelas 7–9 SMP', label: 'Kelas 7–9 SMP' },
          { value: 'Kelas 10–12 SMA', label: 'Kelas 10–12 SMA' },
        ],
      },
      {
        id: 'gaya',
        label: 'Gaya Penyampaian',
        type: 'select',
        required: true,
        options: [
          { value: 'Penjelasan sederhana', label: 'Penjelasan sederhana' },
          { value: 'Analogi sehari-hari', label: 'Analogi sehari-hari' },
          { value: 'Poin-poin ringkas', label: 'Poin-poin ringkas' },
          { value: 'Cerita / narasi', label: 'Cerita / narasi' },
        ],
      },
    ],
  },
  {
    id: 'komentar-rapor',
    title: 'Komentar Rapor',
    description: 'Hasilkan 3 alternatif komentar rapor yang apresiatif dan membangun untuk setiap siswa.',
    Icon: MessageSquare,
    fields: [
      { id: 'namaSiswa', label: 'Nama Siswa (opsional)', type: 'text', placeholder: 'contoh: Budi' },
      { id: 'aspek', label: 'Aspek / Mata Pelajaran', type: 'text', placeholder: 'contoh: Matematika, sikap belajar', required: true },
      { id: 'catatan', label: 'Catatan tentang Siswa', type: 'textarea', placeholder: 'Kekuatan, area pengembangan, pencapaian khusus...', required: true, rows: 4 },
      {
        id: 'nada',
        label: 'Nada Komentar',
        type: 'select',
        required: true,
        options: [
          { value: 'Apresiatif dan membangun', label: 'Apresiatif dan membangun' },
          { value: 'Formal dan objektif', label: 'Formal dan objektif' },
          { value: 'Hangat dan personal', label: 'Hangat dan personal' },
        ],
      },
      { id: 'islami', label: 'Sertakan nuansa Islami', type: 'toggle', description: 'Tambahkan kalimat bernuansa Islami yang positif.' },
    ],
  },
  {
    id: 'ide-kegiatan',
    title: 'Ide Kegiatan',
    description: 'Dapatkan 4 ide kegiatan seru, aman, dan hemat biaya untuk energi kelas.',
    Icon: Zap,
    fields: [
      { id: 'mapelTema', label: 'Mapel / Tema', type: 'text', placeholder: 'contoh: Bahasa Indonesia', required: true },
      {
        id: 'kelas',
        label: 'Kelas',
        type: 'select',
        required: true,
        options: [
          { value: 'Kelas 1–2 SD', label: 'Kelas 1–2 SD' },
          { value: 'Kelas 3–4 SD', label: 'Kelas 3–4 SD' },
          { value: 'Kelas 5–6 SD', label: 'Kelas 5–6 SD' },
          { value: 'Kelas 7–9 SMP', label: 'Kelas 7–9 SMP' },
          { value: 'Kelas 10–12 SMA', label: 'Kelas 10–12 SMA' },
        ],
      },
      { id: 'tujuan', label: 'Tujuan Kegiatan', type: 'text', placeholder: 'contoh: Membangun kerja sama tim', required: true },
      {
        id: 'jenisKegiatan',
        label: 'Jenis Kegiatan',
        type: 'select',
        required: true,
        options: [
          { value: 'Ice Breaker', label: 'Ice Breaker' },
          { value: 'Kerja Kelompok', label: 'Kerja Kelompok' },
          { value: 'Permainan Edukatif', label: 'Permainan Edukatif' },
          { value: 'Proyek Mini', label: 'Proyek Mini' },
        ],
      },
    ],
  },
  {
    id: 'komunikasi-ortu',
    title: 'Komunikasi Orang Tua',
    description: 'Buat pesan atau surat untuk orang tua yang sopan, jelas, dan siap kirim.',
    Icon: Mail,
    fields: [
      { id: 'tujuanPesan', label: 'Tujuan Pesan', type: 'text', placeholder: 'contoh: Informasi kemajuan belajar anak', required: true },
      { id: 'konteks', label: 'Konteks Singkat', type: 'textarea', placeholder: 'Detail situasi, nama siswa (opsional), informasi yang ingin disampaikan...', required: true, rows: 4 },
      {
        id: 'kanal',
        label: 'Kanal Pengiriman',
        type: 'select',
        required: true,
        options: [
          { value: 'WhatsApp', label: 'WhatsApp' },
          { value: 'Surat Resmi', label: 'Surat Resmi' },
        ],
      },
      {
        id: 'nada',
        label: 'Nada Pesan',
        type: 'select',
        required: true,
        options: [
          { value: 'Ramah dan hangat', label: 'Ramah dan hangat' },
          { value: 'Formal dan profesional', label: 'Formal dan profesional' },
        ],
      },
    ],
  },
]
